mqtt:
  client:
    protocol: 4               # MQTTv311
  connection:
    host: eagle-creative.com  # Broker Address
    port: 1883                # Broker Port
    keepalive: 60
  account:
    username: HSA
    password: Doris3000




bridge:
#Standard bridges
  # pose
  - factory: mqtt_bridge.bridge:RosToMqttBridge   # Forward from ROS to MQTT
    msg_type: geometry_msgs.msg:Pose
    topic_from: /rdg01/pose                  # ROS topic
    topic_to: HSA/ros/rdg01/pose                      # MQTT topic
  - factory: mqtt_bridge.bridge:MqttToRosBridge   # Forward MQTT to ROS
    msg_type: geometry_msgs.msg:PoseWithCovarianceStamped
    topic_from: unity/rdg01/pose                  # MQTT topic
    topic_to: /unity/pose                         # ROS topic
  - factory: mqtt_bridge.bridge:RosToMqttBridge   # Forward from ROS to MQTT
    msg_type: geometry_msgs.msg:Pose
    topic_from: /rdg02/pose                  # ROS topic
    topic_to: HSA/ros/rdg02/pose                      # MQTT topic
  - factory: mqtt_bridge.bridge:MqttToRosBridge   # Forward MQTT to ROS
    msg_type: geometry_msgs.msg:PoseWithCovarianceStamped
    topic_from: unity/rdg02/pose                  # MQTT topic
    topic_to: /unity/pose                         # ROS topic


